name: Build and Run Tests

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:

  # Build waterbox and cores
  build-waterbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
       submodules: recursive
    - name: Installing clang 18
      run: wget https://apt.llvm.org/llvm.sh;
           chmod u+x llvm.sh;
           sudo ./llvm.sh 18;
           clang-18 --version;
    - name: Getting musl
      run: git submodule init waterbox/musl;
           git submodule update waterbox/musl
    - name: Building musl
      working-directory: ./waterbox/musl
      env:
        CC: clang-18
        CXX: clang++-18
      run: ./wbox_configure.sh;
           ./wbox_build.sh;
    - name: Building emulibc
      working-directory: ./waterbox/emulibc
      env:
        CC: clang-18
        CXX: clang++-18
      run: make
    - name: Building libco
      working-directory: ./waterbox/libco
      env:
        CC: clang-18
        CXX: clang++-18
      run: make
    - name: Building libcxx
      working-directory: ./waterbox/libcxx
      env:
        CC: clang-18
        CXX: clang++-18
      run: ./do-everything.sh
    - name: Building nyma
      working-directory: ./waterbox/nyma
      env:
        CC: clang-18
        CXX: clang++-18
      run: ./build-and-install-zlib.sh
    - name: Building all waterboxed cores
      working-directory: ./waterbox
      env:
        CC: clang-18
        CXX: clang++-18
      run: INCLUDE_MAME=1 ./make-all-cores.sh