name: Build mame (waterbox)

on:
  pull_request:
    branches: [ "master" ]
    paths: [ "waterbox/emulibc/**", "waterbox/libco/**", "waterbox/libcxx/**", "waterbox/musl/**", "waterbox/*", "waterbox/mame-arcade/**" ]
  push:
    branches: [ "master" ]
    paths: [ "waterbox/emulibc/**", "waterbox/libco/**", "waterbox/libcxx/**", "waterbox/musl/**", "waterbox/*", "waterbox/mame-arcade/**" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CC: clang-18

jobs:

  build-waterbox:
    uses: ./.github/workflows/waterbox.yml

  build-mame:
    runs-on: ubuntu-latest
    needs: build-waterbox
    steps:
    - uses: actions/checkout@v4
    - name: Getting submodule(s)
      working-directory: ./waterbox/
      run: git submodule update --init mame-arcade/mame
    - name: Install clang 18
      run: wget https://apt.llvm.org/llvm.sh;
            chmod u+x llvm.sh;
            sudo ./llvm.sh 18;
            clang-18 --version;
    - name: Download compiled waterbox
      uses: actions/download-artifact@v4
      with:
        name: compiled-waterbox
        path: waterbox/sysroot
    - name: Give execution permission to compiler
      working-directory: ./waterbox/sysroot
      run: chmod u+x bin/*
    - name: Build emulibc
      working-directory: ./waterbox/emulibc
      run: make -j
    - name: Build libco
      working-directory: ./waterbox/libco
      run: make -j
    - name: Build MAME
      working-directory: ./waterbox/mame-arcade
      run: make -j4 install
    - name: Upload mame core
      uses: actions/upload-artifact@v4
      with:
        name: mame-core
        path: |
          Assets/dll/libmamearcade.wbx.zst
